# Generated by Django 5.2 on 2025-05-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_crawlertask_components_identified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlertask',
            name='depth',
            field=models.IntegerField(default=2, verbose_name='爬取深度（已废弃）'),
        ),
    ]
