# Generated by Django 5.2 on 2025-05-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_crawlertask_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlertask',
            name='link_timeout',
            field=models.IntegerField(default=30, verbose_name='单个链接超时时间(秒)'),
        ),
        migrations.AddField(
            model_name='crawlertask',
            name='resource_timeout',
            field=models.IntegerField(default=15, verbose_name='单个资源超时时间(秒)'),
        ),
        migrations.AddField(
            model_name='crawlertask',
            name='task_timeout',
            field=models.IntegerField(default=1800, verbose_name='任务超时时间(秒)'),
        ),
        migrations.AlterField(
            model_name='crawlertask',
            name='status',
            field=models.CharField(choices=[('queued', '排队中'), ('link_crawling', '链接爬取中'), ('content_crawling', '内容爬取中'), ('resource_crawling', '资源爬取中'), ('fingerprint_matching', '指纹匹配中'), ('completed', '已完成'), ('failed', '失败'), ('timeout', '已超时')], default='queued', max_length=20, verbose_name='任务状态'),
        ),
    ]
