# Generated by Django 5.2 on 2025-05-05 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_task', '创建任务'), ('login', '登录'), ('logout', '登出'), ('submit_fingerprint', '提交指纹'), ('approve_fingerprint', '审核指纹'), ('task_status_change', '任务状态变更'), ('component_identified', '识别组件'), ('other', '其他操作')], max_length=30, verbose_name='操作类型')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('failure', '失败')], max_length=10, verbose_name='状态')),
                ('message', models.TextField(blank=True, verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
