# Generated by Django 5.2 on 2025-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_systemlog_action_alter_systemlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('create_task', '创建任务'), ('login', '登录'), ('logout', '登出'), ('submit_fingerprint', '提交指纹'), ('approve_fingerprint', '审核指纹'), ('task_status_change', '任务状态变更'), ('component_identified', '识别组件'), ('task_debug', '任务调试'), ('user_management', '用户管理'), ('other', '其他操作')], max_length=30, verbose_name='操作类型'),
        ),
    ]
